// <auto-generated />
using System;
using Binding;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Binding.Migrations
{
    [DbContext(typeof(DB))]
    partial class DBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Fired");

                    b.Property<DateTime>("Hired");

                    b.Property<string>("Name");

                    b.Property<int>("PositionId");

                    b.Property<decimal>("Salary");

                    b.Property<string>("Surname");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("employees");

                    b.HasData(
                        new { Id = 1, Fired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Hired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Name = "Holger", PositionId = 1, Salary = 1500m, Surname = "Göpfert" },
                        new { Id = 2, Fired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Hired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Name = "Steffen", PositionId = 2, Salary = 1500m, Surname = "Frommberger" },
                        new { Id = 3, Fired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Hired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Name = "Иван", PositionId = 2, Salary = 2500m, Surname = "Петров" }
                    );
                });

            modelBuilder.Entity("Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PositionName");

                    b.HasKey("Id");

                    b.ToTable("positions");

                    b.HasData(
                        new { Id = 1, PositionName = "Developer" },
                        new { Id = 2, PositionName = "DevOps" }
                    );
                });

            modelBuilder.Entity("Models.Employee", b =>
                {
                    b.HasOne("Models.Position", "PositionOfEpmloyee")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
